import assert from 'node:assert/strict';
import { ProviderUsageHttpError, ProviderUsageTimeoutError } from '../src/lib/provider-usage-request.ts';
import * as selection from '../src/lib/provider-usage-selection.ts';
assert.equal(typeof selection.createProviderUsageSelectionController, 'function');
const revision = 'a'.repeat(64);
const controller = selection.createProviderUsageSelectionController();
const old = controller.beginRead();
assert.equal(controller.beginSave(revision), true);
assert.equal(controller.beginRead(), null, 'no catalog read may start while PUT is pending');
controller.settleSave(false);
let canonical = ['b'];
assert.equal(controller.acceptRead(old, true), false, 'late GET A cannot overwrite PUT B');
if (controller.acceptRead(old, true)) canonical = ['a'];
assert.deepEqual(canonical, ['b']);
assert.equal(controller.acceptRead(controller.beginRead(), true), true);
assert.equal(controller.beginSave(revision), true);
controller.settleSave(true);
assert.equal(controller.beginSave(revision), false, 'uncertain mutation must reconcile before another save');
assert.equal(controller.acceptRead(controller.beginRead(), false), false, 'unusable catalog cannot reconcile uncertainty');
assert.equal(controller.canSave(), false);
assert.equal(controller.acceptRead(controller.beginRead(), true), false, 'a GET without a write fence cannot settle an uncertain PUT');
assert.equal(controller.canSave(), false);
assert.equal(controller.acceptRead(controller.beginRead(), true, revision), true);
assert.equal(controller.canSave(), true);
assert.equal(controller.beginSave(), false, 'never issue an unfenced mutation');
const initial = selection.createProviderUsageSelectionController();
assert.equal(initial.acceptRead(initial.beginRead(), false), true, 'initial discovery failure must remain observable without changing canonical selection');
assert.equal(typeof selection.isProviderUsageSelectionUncertain, 'function');
const auth = new Error('Mission Control requires an access token.'); auth.name = 'MissionControlAuthError';
assert.equal(selection.isProviderUsageSelectionUncertain(auth), false, 'known 401 rejection did not apply a mutation');
assert.equal(selection.isProviderUsageSelectionUncertain(new TypeError('Network failed')), true);
assert.equal(selection.isProviderUsageSelectionUncertain(new ProviderUsageTimeoutError()), true);
assert.equal(selection.isProviderUsageSelectionUncertain(new ProviderUsageHttpError(500)), true, 'server failure may occur after commit');
assert.equal(selection.isProviderUsageSelectionUncertain(new ProviderUsageHttpError(409)), false, 'CAS conflict did not write');
assert.equal(selection.isProviderUsageSelectionUncertain(new Error('Malformed PUT response')), true);
console.log('selection generations and uncertain PUT reconciliation passed');
