import assert from 'node:assert/strict';
import * as refresh from '../src/lib/provider-usage-refresh.ts';
const provider = (id, value, available = true) => ({ provider: id, available, windows: [{ id: 'primary', label: 'Quota', usedPercent: value }], balances: [], metrics: [] });
const current = { success: true, available: true, providers: [provider('broken', 10), provider('healthy', 10), provider('removed', 10)] };
const next = { success: true, available: true, providers: [{ ...provider('broken', 0, false), windows: [], error: 'Malformed', warnings: ['invalid_field'], lastAttemptAt: '2026-10-06T01:00:00Z' }, provider('healthy', 20)] };
assert.equal(typeof refresh.mergeProviderUsageSnapshot, 'function', 'per-provider merge is required');
const result = refresh.mergeProviderUsageSnapshot(current, next);
assert.equal(result.providers[0].windows[0].usedPercent, 10);
assert.equal(result.providers[0].stale, true);
assert.equal(result.providers[0].error, 'Malformed');
assert.equal(result.providers[1].windows[0].usedPercent, 20);
assert.equal(result.providers.some(p => p.provider === 'removed'), false);
const noData = { ...next, available: false, providers: [{ ...provider('broken', 0, false), windows: [], dataState: 'no_data' }] };
assert.equal(refresh.mergeProviderUsageSnapshot(current, noData).providers[0].dataState, 'no_data', 'valid empty provider response is not a transport failure');
const partial = { ...next, providers: [{ ...provider('broken', 0), windows: [], balances: [{ id: 'balance', label: 'Balance', value: 5 }], warnings: ['invalid_field'], malformedFields: { windows: ['*'] } }, provider('healthy', 25)] };
const partialResult = refresh.mergeProviderUsageSnapshot(current, partial);
assert.equal(partialResult.providers[0].windows[0]?.usedPercent, 10, 'partially malformed provider must retain its last-good snapshot, not erase prior fields');
assert.equal(partialResult.providers[0].stale, true);
assert.equal(partialResult.providers[0].balances[0].value, 5, 'valid fields update despite a damaged quota');
assert.equal(partialResult.providers[1].windows[0].usedPercent, 25);
console.log('per-provider last-good merge passed');
